### ISSUE TITLE
Application Frame

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-marketplace-demo#121]
### Start Up
 - [x] Launch Screens - design - ?, implementation - 4 #133
 - [x] Intro Animations - design - ?, implementation - 16 #132

### MainPage
 - [x] Navigation Bar Redesign - implementation - 2 #123
 - [x] ListView Redesign - implementation - 2 #126
 - [x] ~~Example Images - design - 3, implementation - 3~~ (duplicate)

### GroupPage
 - [x] ~~Use the same design as the MainPage - ???~~

### SideDrawer
 - [x] ~~Must be full-screen - research implementation - 4, implementation - ?~~ (we can drop this) #48 
 - [x] Redesign. Use same content. (Requires control grouping) - design - 2, implementation - 4 - #129

### ExamplePage
 - [x] Redesign the SideBar - design - 1, implementation - 2
 - [x] Add the ExampleMenu and Back button to each example ActionBar - implementation - 8

### Info pages
 - [x] About - Redesign - design - 1, implementation - 1
 - [x] ExampleInformation - Redesign - implementation - 1
 - [x] ExampleCode - Redesign - implementation - 2
