### ISSUE TITLE
Examples

### ISSUE THREAD

**Issue by PanayotCankov** [NativeScript/nativescript-marketplace-demo#122]
### Layouts
 - [x] Redesign - 2
 - [x] Implement the redesign - 2 - #134
 - [x] MainPage Image

### User Profile
 - [x] Redesign - 2
 - [x] Implement the redesign - 4 - https://github.com/NativeScript/nativescript-marketplace-demo/issues/135
 - [x] MainPage Image

### Conference Agenda
 - [x] Redesign - 2
 - [x] Implement the redesign - 2 - https://github.com/NativeScript/nativescript-marketplace-demo/issues/142
 - [x] MainPage Image

### Bar Series
 - [x] Redesign - 4
 - [x] Implement the redesign - #148
 - [x] MainPage Image

### Line Series
 - [x] Redesign - 3
 - [x] Implement the redesign - #148
 - [x] MainPage Image

### Area Series
 - [x] Redesign - 3
 - [x] Implement the redesign - #148
 - [x] MainPage Image

### Pie Series
 - [x] Redesign - 3
 - [x] Implement the redesign - #148
 - [x] MainPage Image

### Item Layouts
 - [x] Redesign - 1
 - [x] Implement the redesign - #151 
 - [x] MainPage Image

### Item Reorder
 - [x] Redesign - 2
 - [x] Implement the redesign - #157
 - [x] MainPage Image

### Selection
 - [x] Redesign - 3
 - [x] Implement the redesign - #160
 - [x] MainPage Image
